import {db} from './supabase.js';
const $=x=>document.getElementById(x), show=id=>['auth','shelf','editor','reader'].forEach(x=>$(x).classList.toggle('hidden',x!==id));
let user=null,editing=null,books=[],chunks=[],spread=0,scene=null;
async function refresh(){const r=await db.from('books').select('*').order('created_at',{ascending:false});if(r.error){$('shelfMsg').textContent=r.error.message;return}books=r.data||[];$('books').innerHTML='';for(const b of books){let img='';if(b.cover_path){const s=await db.storage.from('book-covers').createSignedUrl(b.cover_path,3600);img=s.data?.signedUrl||''}const el=document.createElement('article');el.className='book';el.innerHTML=`<div class="cover">${img?`<img src="${img}" alt="">`:'📖'}</div><div class="info"><b>${esc(b.title)}</b><div>${esc(b.author||'')}</div></div><div class="actions"><button data-open>Read</button><button data-edit class="secondary">Edit</button></div>`;el.querySelector('[data-open]').onclick=()=>openReader(b);el.querySelector('[data-edit]').onclick=()=>edit(b);$('books').append(el)}}
const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('login').onclick=async()=>{msg('authMsg','Logging in…');const r=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(r.error)msg('authMsg',r.error.message)};
$('signup').onclick=async()=>{msg('authMsg','Creating account…');const r=await db.auth.signUp({email:$('email').value.trim(),password:$('password').value});if(r.error)msg('authMsg',r.error.message);else msg('authMsg',r.data.session?'Account created.':'Check your email to confirm your account.')};
$('logout').onclick=()=>db.auth.signOut();$('add').onclick=()=>edit();$('back').onclick=$('cancel').onclick=()=>show('shelf');
function edit(b=null){editing=b;$('editHeading').textContent=b?'Edit book':'Add book';$('bookId').value=b?.id||'';$('title').value=b?.title||'';$('author').value=b?.author||'';$('description').value=b?.description||'';$('cover').value='';$('editMsg').textContent='';show('editor')}
$('save').onclick=async()=>{try{msg('editMsg','Saving…');if(!user)throw Error('Not logged in');let path=editing?.cover_path||null,f=$('cover').files[0];if(f){const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');path=`${user.id}/${crypto.randomUUID()}.${ext||'jpg'}`;let u=await db.storage.from('book-covers').upload(path,f,{upsert:false,contentType:f.type});if(u.error)throw u.error}let payload={title:$('title').value.trim(),author:$('author').value.trim()||null,description:$('description').value.trim()||null,cover_path:path};let r=editing?await db.from('books').update(payload).eq('id',editing.id).select().single():await db.from('books').insert({...payload,user_id:user.id}).select().single();if(r.error)throw r.error;show('shelf');await refresh()}catch(e){msg('editMsg',e.message)}};
$('local').onchange=e=>e.target.files[0]&&startLocal(e.target.files[0]);$('readerFile').onchange=e=>e.target.files[0]&&startLocal(e.target.files[0]);
async function openReader(b){$('readerTitle').textContent=b.title;$('readerFile').value='';show('reader');$('readerFile').click()}
async function startLocal(file){show('reader');$('status').textContent='Parsing locally…';try{chunks=file.name.toLowerCase().endsWith('.pdf')?await parsePdf(file):await parseEpub(file);spread=0;buildAR();$('status').textContent='Point camera at the Hiro marker. Swipe to turn pages.';update()}catch(e){$('status').textContent=e.message}}
function split(t,n=350){t=t.replace(/\r/g,'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();let a=[];while(t){let i=t.length<=n?t.length:t.lastIndexOf(' ',n);if(i<Math.floor(n*.6))i=Math.min(n,t.length);a.push(t.slice(0,i).trim());t=t.slice(i).trim()}return a.filter(Boolean)}
async function parseEpub(f){let z=await JSZip.loadAsync(await f.arrayBuffer()),c=await z.file('META-INF/container.xml').async('text'),d=new DOMParser().parseFromString(c,'application/xml'),rf=d.querySelector('rootfile');if(!rf)throw Error('Invalid EPUB container');let op=rf.getAttribute('full-path'),od=new DOMParser().parseFromString(await z.file(op).async('text'),'application/xml'),m=new Map();od.querySelectorAll('manifest>item').forEach(i=>m.set(i.getAttribute('id'),i));let base=op.split('/').slice(0,-1).join('/'),out=[];for(const r of od.querySelectorAll('spine>itemref')){let i=m.get(r.getAttribute('idref'));if(!i||!/xhtml|html/i.test(i.getAttribute('media-type')||''))continue;let p=base?base+'/'+i.getAttribute('href'):i.getAttribute('href'),e=z.file(p);if(!e)continue;let x=new DOMParser().parseFromString(await e.async('text'),'text/html');x.querySelectorAll('script,style,nav').forEach(n=>n.remove());out.push(x.body?.innerText||'')}let a=split(out.join('\n\n'));if(!a.length)throw Error('No readable text found');return a}
async function parsePdf(f){const pdf=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');const p=await pdf.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise,out=[];for(let i=1;i<=p.numPages;i++){let pg=await p.getPage(i),c=await pg.getTextContent();out.push(c.items.map(x=>x.str).join(' '))}return split(out.join('\n\n'))}
function buildAR(){if(scene){scene.remove()}$('ar').innerHTML='';scene=document.createElement('a-scene');scene.setAttribute('embedded','');scene.setAttribute('vr-mode-ui','enabled:false');scene.setAttribute('renderer','colorManagement:true;precision:mediump');scene.setAttribute('arjs','sourceType: webcam; facingMode: environment; debugUIEnabled: false;');let marker=document.createElement('a-marker');marker.setAttribute('preset','hiro');let book=document.createElement('a-entity');let spine=document.createElement('a-box');spine.setAttribute('position','0 0.05 0');spine.setAttribute('width','.06');spine.setAttribute('height','.05');spine.setAttribute('depth','.78');spine.setAttribute('color','#252a32');book.append(spine);for(const x of [-.29,.29]){let p=document.createElement('a-box');p.setAttribute('position',`${x} .02 0`);p.setAttribute('width','.52');p.setAttribute('height','.012');p.setAttribute('depth','.78');p.setAttribute('color','#f7f4eb');book.append(p)};for(const x of [-.29,.29]){let t=document.createElement('a-text');t.setAttribute('id',x<0?'leftText':'rightText');t.setAttribute('position',`${x} .031 0`);t.setAttribute('rotation','-90 0 0');t.setAttribute('width','.43');t.setAttribute('height','.65');t.setAttribute('color','#111');t.setAttribute('align','left');t.setAttribute('baseline','top');t.setAttribute('wrap-count','38');book.append(t)}marker.append(book);scene.append(marker);let cam=document.createElement('a-entity');cam.setAttribute('camera','');cam.setAttribute('look-controls-enabled','false');scene.append(cam);$('ar').append(scene)}
function update(){$('leftText')?.setAttribute('value',chunks[spread*2]||'');$('rightText')?.setAttribute('value',chunks[spread*2+1]||'');$('pages').textContent=`${spread*2+1}–${Math.min(chunks.length,spread*2+2)} / ${chunks.length}`}
$('prev').onclick=()=>{spread=Math.max(0,spread-1);update()};$('next').onclick=()=>{spread=Math.min(Math.ceil(chunks.length/2)-1,spread+1);update()};$('close').onclick=()=>{if(scene)scene.remove();scene=null;show('shelf')};$('help').onclick=()=>$('modal').classList.remove('hidden');$('modalClose').onclick=()=>$('modal').classList.add('hidden');
let sx=null;$('reader').addEventListener('touchstart',e=>{if(e.touches.length===1)sx=e.touches[0].clientX},{passive:true});$('reader').addEventListener('touchend',e=>{if(sx==null)return;let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45){spread=Math.max(0,Math.min(Math.ceil(chunks.length/2)-1,spread+(dx<0?1:-1)));update()}sx=null},{passive:true});
function msg(id,t){$(id).textContent=t}db.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user){show('shelf');await refresh()}else show('auth')});let s=(await db.auth.getSession()).data.session;user=s?.user||null;if(user){show('shelf');await refresh()}else show('auth');
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(console.warn);
